import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/contexts/app.context";
import SiderBar from "@/components/sidebar";
import Nav from "@/components/nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className="bg-gray-50 dark:bg-gray-800">
        <AppProvider>
          <Nav />
          <SiderBar />
          <div
            id="main-content"
            className="relative w-full h-full overflow-y-auto bg-gray-50 lg:ml-64 dark:bg-gray-900"
          >
            <main>{children}</main>
          </div>
        </AppProvider>
        <script
          async
          src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"
        ></script>
      </body>
    </html>
  );
}
